name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: Updates
    labels:
      - chore

change-template: '- $TITLE (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
