name: finos-parent-pom-build

env:
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-mvn-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up JDK and GPG
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        java-package: jdk
        server-id: ossrh
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
        gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
        gpg-passphrase: CI_GPG_PASSPHRASE

    - name: Configure git
      run: |
        git config --global committer.email "infra@finos.org"
        git config --global committer.name "FINOS Admin"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"

    - name: Download deps and plugins
      run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

    - name: Build + Test
      if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main'
      run: mvn install

    - name: Build + Test + Sonar
      if: github.ref == 'refs/heads/dev'
      run: mvn install -Psonar

    - name: Build + Test + Sonar + Maven Deploy
      if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[maven-release-plugin]')
      run: mvn deploy -Psonar -Dsonar.projectKey=finos_finos-parent-pom

    - name: Diagnostic check before release
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Checking ~/.m2/settings.xml:"
        cat ~/.m2/settings.xml || echo "No settings.xml found"
        echo "Checking GPG keys:"
        gpg --list-keys || echo "No GPG keys found"

    - name: Prepare release
      if: github.ref == 'refs/heads/main'
      run: mvn -B -DpreparationGoals=clean release:prepare -Prelease -DinteractiveMode=false

    - name: Perform release
      if: github.ref == 'refs/heads/main'
      run: mvn -B release:perform -Prelease -DinteractiveMode=false
