name: finos-parent-pom-build

env:
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'pom.xml'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    # Not sure why this is here
    # - name: Install Node
    #   uses: actions/setup-node@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      env:
        cache-name: cache-mvn-deps
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        java-package: jdk
        distribution: temurin
        server-id: ossrh
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
        gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
        gpg-passphrase: CI_GPG_PASSPHRASE
    - name: Configure git
      run: |
        git config --global committer.email "infra@finos.org"
        git config --global committer.name "FINOS Admin"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - name: Download deps and plugins
      run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
    - name: Build + Test
      if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main'
      run: mvn install
    - name: Build + Test + Sonar
      if: github.ref == 'refs/heads/dev'
      run: mvn install -Psonar
    - name: Build + Test + Sonar + Maven Deploy
      if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message,'[maven-release-plugin]')
      run: mvn deploy -Psonar -Dsonar.projectKey=finos_finos-parent-pom

    - name: Prepare release
      if: github.ref == 'refs/heads/main'
      run: mvn -B -DpreparationGoals=clean release:prepare -Prelease -DinteractiveMode=false

    - name: Perform release
      if: github.ref == 'refs/heads/main'
      run: mvn -B release:perform -Prelease -DinteractiveMode=false